---
language: python
python:
  - "3.7"
services: docker

env:
  global:
    - ORG_NAME: alpha29
    - ROLE_NAME: base
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: centos7

install:
  - pip install -r requirements.txt

before_script:
  - cd ../
  - mv ansible-role-$ORG_NAME-$ROLE_NAME $ORG_NAME.$ROLE_NAME
  - cd $ORG_NAME.$ROLE_NAME

script:
  - molecule test

notifications:
  email:
    recipients:
      - cbrown@alpha29.com
