---
- name: update everything (yum)
  when:
    - ansible_os_family == 'RedHat'
  yum:
    update_cache: yes
    name: '*'
    state: latest

- name: update everything (apt)
  when:
    - ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    name: '*'
    state: latest

#- name: install pkgconfig (yum)
#  when:
#    - ansible_os_family == 'RedHat'
#  yum:
#    name: pkgconfig

- name: install pkg-config (apt)
  when:
    - ansible_os_family == 'Debian'
  apt:
    name: pkg-config

- name: install build tools
  include_role:
    name: robertdebock.buildtools

- name: unarchive file
  unarchive:
    src: "https://github.com/vcftools/vcftools/releases/download/v0.{{ vcftools_version }}/vcftools-0.{{ vcftools_version }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: configure
  command: "./configure"
  args:
    chdir: "/tmp/vcftools-0.{{ vcftools_version }}"

- name: run make
  make:
    chdir: "/tmp/vcftools-0.{{ vcftools_version }}"

- name: run make install
  make:
    chdir: "/tmp/vcftools-0.{{ vcftools_version }}"
    target: install
