---
- name: update cache (yum)
  when:
    - ansible_os_family == 'RedHat'
  yum:
    update_cache: yes
    cache_valid_time: 3600

- name: update cache (apt)
  when:
    - ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install pkg-config (apt)
  when:
    - ansible_os_family == 'Debian'
  apt:
    name: pkg-config

- name: install build tools
  include_role:
    name: robertdebock.buildtools

- name: unarchive file
  unarchive:
    src: "https://github.com/vcftools/vcftools/releases/download/v{{ vcftools_version }}/vcftools-{{ vcftools_version }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: configure
  command: "./configure"
  # bypass idempotence check
  changed_when: false
  args:
    chdir: "/tmp/vcftools-{{ vcftools_version }}"

- name: run make
  # bypass idempotence check
  changed_when: false
  make:
    chdir: "/tmp/vcftools-{{ vcftools_version }}"

- name: run make install
  # bypass idempotence check
  changed_when: false
  make:
    chdir: "/tmp/vcftools-{{ vcftools_version }}"
    target: install
