---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include ansible-role-alpha29-vcftools"
      include_role:
        name: "ansible-role-alpha29-vcftools"
